name: 'Build Image'
description: 'Build Docker image and push to registry'

inputs:
  image-name:
    description: 'Name of the Docker image'
    required: true
  src-dir:
    description: 'The path of the directory containing the Docker image source code'
    required: true

runs:
  using: 'composite'
  steps:
    # TODO: this step is already in the "main" GA - should I have it here as well?
    #- name: 🐧 Checkout
    #uses: actions/checkout@v3

    - name: 📦 Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 🐳 Login to docker.01-edu.org Registry
      uses: docker/login-action@v2
      with:
        registry: docker.01-edu.org
        username: ${{ secrets.USER_DOCKER_01EDU_ORG }}
        password: ${{ secrets.SECRET_DOCKER_01EDU_ORG }}

    - name: 🏗️ Build Docker image and push to registry
      shell: bash
      run: |
        docker build "$SRC_DIR" --file "$SRC_DIR/Dockerfile" --tag "$IMAGE_NAME" 
        docker push "$IMAGE_NAME"
      env:
        IMAGE_NAME: ${{ inputs.image-name }}
        SRC_DIR: ${{ inputs.src-dir }}
