name: "Build Image"
description: "Build Docker image and push to registry"

inputs:
  image-name:
    description: "Name of the Docker image"
    required: true
  src-dir:
    description: "The path of the directory containing the Docker image source code"
    required: true
  gh-token:
    description: "The GitHub token"
    required: true
  docker-un:
    description: "The 01 DockerHub Username"
    required: true
  docker-pw:
    description: "The 01 DockerHub Password"
    required: true

runs:
  using: "composite"
  steps:
    - name: 📦 Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.gh-token }}

    - name: 🐳 Login to docker.01-edu.org Registry
      uses: docker/login-action@v3
      with:
        registry: docker.01-edu.org
        username: ${{ inputs.docker-un }}
        password: ${{ inputs.docker-pw }}

    - name: 🏗️ Build Docker image and push to registry
      shell: bash
      run: |
        docker build "$SRC_DIR" --file "$SRC_DIR"Dockerfile --tag "$IMAGE_NAME" 
        docker push "$IMAGE_NAME"
      env:
        IMAGE_NAME: ${{ inputs.image-name }}
        SRC_DIR: ${{ inputs.src-dir }}
